/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An array of holders and their data
 */
export type Holders = HolderWrapper[];

/**
 * A JSON schema for defining test data files that can be used to seed a mock, or test, implementation of a Data Holder for the Consumer Data Right
 */
export interface ConsumerDataRightTestDataJSONSchema {
  /**
   * The version of the file formatted using semver (without extensions)
   */
  fileVersion: string;
  /**
   * The version of the CDR standards that these tests are validated for.  For formatted using semver (without extensions)
   */
  standardsVersion: string;
  /**
   * A short title of the test data file
   */
  title: string;
  /**
   * An optional description of the test data file to identify its purpose
   */
  description?: string;
  holders?: Holders;
  /**
   * A cache of previously registered clients
   */
  clientCache?: Client[];
  /**
   * A cache of previously loaded recipients from the CDR Register
   */
  registerCache?: Recipient[];
}
/**
 * A wrapper for a single holder to contain all of the data related to the holder
 */
export interface HolderWrapper {
  /**
   * The unique internal ID of the holder
   */
  holderId: string;
  holder: Holder;
}
/**
 * Data for a single data holder
 */
export interface Holder {
  unauthenticated: Unauthenticated;
  authenticated: Authenticated;
}
/**
 * Unauthenticated data for a single data holder
 */
export interface Unauthenticated {
  /**
   * Unauthenticated banking data
   */
  banking?: {
    /**
     * An array of banking products
     */
    products?: BankProduct[];
  };
  /**
   * Unauthenticated energy data
   */
  energy?: {
    /**
     * An array of energy plans
     */
    plans?: EnergyPlan[];
  };
  /**
   * Current system status
   */
  admin?: {
    status?: AdminStatus;
    /**
     * An array of planned outages
     */
    outages?: AdminOutage[];
  };
}
/**
 * A bank product aligned to the current version of the data standards
 */
export interface BankProduct {
  [k: string]: unknown;
}
/**
 * An energy plan aligned to the current version of the data standards
 */
export interface EnergyPlan {
  [k: string]: unknown;
}
/**
 * A status object for the holder
 */
export interface AdminStatus {
  [k: string]: unknown;
}
/**
 * A planned outage object for the holder
 */
export interface AdminOutage {
  [k: string]: unknown;
}
/**
 * Authenticated data for a single data holder
 */
export interface Authenticated {
  /**
   * An array of customers and their data
   */
  customers?: CustomerWrapper[];
}
/**
 * A wrapper for a single customer to contain all of the data related to the customer
 */
export interface CustomerWrapper {
  /**
   * The unique internal ID of the customer
   */
  customerId: string;
  customer: Customer;
  /**
   * Banking data for this customer
   */
  banking?: {
    /**
     * An array of accounts and their data
     */
    accounts?: BankAccountWrapper[];
    /**
     * An array of direct debit authorisations
     */
    directDebits?: BankDirectDebit[];
    /**
     * An array of payees
     */
    payees?: BankPayee[];
    /**
     * An array of payment schedules
     */
    payments?: BankPaymentSchedule[];
    [k: string]: unknown;
  };
  /**
   * Energy data for this customer
   */
  energy?: {
    /**
     * An array of accounts and their data
     */
    accounts?: EnergyAccountWrapper[];
    /**
     * An array of service points and their data
     */
    servicePoints?: EnergyServicePointWrapper[];
    [k: string]: unknown;
  };
}
/**
 * A customer record aligned to the current version of the data standards
 */
export interface Customer {
  [k: string]: unknown;
}
/**
 * A wrapper for a single bank account to contain all of the data related to the account
 */
export interface BankAccountWrapper {
  account: BankAccount;
  balance: BankAccountBalance;
  /**
   * An array of transactions for the account
   */
  transactions?: BankTransaction[];
}
/**
 * A bank account aligned to the current version of the data standards
 */
export interface BankAccount {
  [k: string]: unknown;
}
/**
 * A balance for a bank account aligned to the current version of the data standards
 */
export interface BankAccountBalance {
  [k: string]: unknown;
}
/**
 * A bank transaction aligned to the current version of the data standards
 */
export interface BankTransaction {
  [k: string]: unknown;
}
/**
 * A direct debit authorisation aligned to the current version of the data standards
 */
export interface BankDirectDebit {
  [k: string]: unknown;
}
/**
 * A payee aligned to the current version of the data standards
 */
export interface BankPayee {
  [k: string]: unknown;
}
/**
 * A payment schedule aligned to the current version of the data standards
 */
export interface BankPaymentSchedule {
  [k: string]: unknown;
}
/**
 * A wrapper for a single eenrgy account to contain all of the data related to the account
 */
export interface EnergyAccountWrapper {
  account: EnergyAccount;
  balance: EnergyAccountBalance;
  paymentSchedule?: EnergyPaymentSchedule;
  /**
   * An array of invoices for the account
   */
  invoices?: EnergyInvoice[];
  /**
   * An array of transactions for the account
   */
  transactions?: EnergyTransaction[];
  /**
   * An array of concessions for the account
   */
  concessions?: EnergyConcession[];
}
/**
 * An energy account aligned to the current version of the data standards
 */
export interface EnergyAccount {
  [k: string]: unknown;
}
/**
 * An energy account balance structure aligned to the current version of the data standards
 */
export interface EnergyAccountBalance {
  [k: string]: unknown;
}
/**
 * An energy payment schedule structure aligned to the current version of the data standards
 */
export interface EnergyPaymentSchedule {
  [k: string]: unknown;
}
/**
 * An energy invoice aligned to the current version of the data standards
 */
export interface EnergyInvoice {
  [k: string]: unknown;
}
/**
 * An energy transaction aligned to the current version of the data standards
 */
export interface EnergyTransaction {
  [k: string]: unknown;
}
/**
 * An energy concession aligned to the current version of the data standards
 */
export interface EnergyConcession {
  [k: string]: unknown;
}
/**
 * An energy for a single service point (metering site) to contain all of the data related to the service point
 */
export interface EnergyServicePointWrapper {
  servicePoint?: EnergyServicePoint;
  der?: EnergyDerData;
  /**
   * An array of reads for the service point
   */
  usage?: EnergyUsageRead[];
}
/**
 * Standing data for an energy service point aligned to the current version of the data standards
 */
export interface EnergyServicePoint {
  [k: string]: unknown;
}
/**
 * Distributed energy resources for an energy account aligned to the current version of the data standards
 */
export interface EnergyDerData {
  [k: string]: unknown;
}
/**
 * A usage read for a service point aligned to the current version of the data standards
 */
export interface EnergyUsageRead {
  [k: string]: unknown;
}
/**
 * A previously registered client aligned to the current version of the data standards
 */
export interface Client {
  [k: string]: unknown;
}
/**
 * A recipient record from the CDR Register aligned to the current version of the data standards
 */
export interface Recipient {
  [k: string]: unknown;
}
