/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A JSON schema for defining test data files that can be used to seed a mock, or test, implementation of a Data Holder for the Consumer Data Right
 */
export interface ConsumerDataRightTestDataJSONSchema {
  /**
   * The version of the file formatted using semver (without extensions)
   */
  fileVersion: string;
  /**
   * The version of the CDR standards that these tests are validated for.  For formatted using semver (without extensions)
   */
  standardsVersion: string;
  /**
   * A short title of the test data file
   */
  title: string;
  /**
   * An optional description of the test data file to identify its purpose
   */
  description?: string;
  /**
   * A set of data holders, and their associated data, keyed on data holder ID
   */
  holders?: {
    [k: string]: Holder;
  };
  clientCache?: ClientCache;
  registerCache?: RegisterCache;
}
/**
 * Data for a single data holder
 *
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^[a-zA-Z0-9]+$".
 */
export interface Holder {
  /**
   * Data for a single data holder
   */
  unauthenticated?: {
    unauthenticated?: unknown;
    /**
     * An array of customers and their data
     */
    customers?: unknown[];
  };
}
/**
 * Cache of the previously registered clients for a data holder
 */
export interface ClientCache {
  [k: string]: unknown;
}
/**
 * Cache of the CDR Register meta data to seed the holder with
 */
export interface RegisterCache {
  [k: string]: unknown;
}
