/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type BankProduct = BankingProductV4 & {
  /**
   * An array of bundles that this product participates in.  Each bundle is described by free form information but also by a list of product IDs of the other products that are included in the bundle.  It is assumed that the current product is included in the bundle also
   */
  bundles?: BankingProductBundle[] | null;
  /**
   * Array of features available for the product
   */
  features?: BankingProductFeatureV2[] | null;
  /**
   * Constraints on the application for or operation of the product such as minimum balances or limit thresholds
   */
  constraints?: BankingProductConstraint[] | null;
  /**
   * Eligibility criteria for the product
   */
  eligibility?: BankingProductEligibility[] | null;
  /**
   * Fees applicable for the product
   */
  fees?: BankingProductFee[] | null;
  /**
   * Interest rates available for deposits
   */
  depositRates?: BankingProductDepositRate[] | null;
  /**
   * Interest rates charged against lending balances
   */
  lendingRates?: BankingProductLendingRateV2[] | null;
  [k: string]: unknown;
};
/**
 * Object that contains links to additional information on specific topics
 */
export type BankingProductAdditionalInformationV2 = ({
  [k: string]: unknown;
} & {
  [k: string]: unknown;
} & {
  [k: string]: unknown;
} & {
  [k: string]: unknown;
} & {
  [k: string]: unknown;
}) & {
  /**
   * An array of additional bundles for the product, if applicable. To be treated as secondary documents to the `bundleUri`. Only to be used if there is a primary `bundleUri`.
   */
  additionalBundleUris?: BankingProductAdditionalInformationV2AdditionalInformationUris[] | null;
  /**
   * An array of additional eligibility rules and criteria for the product, if applicable. To be treated as secondary documents to the `eligibilityUri`. Only to be used if there is a primary `eligibilityUri`.
   */
  additionalEligibilityUris?: BankingProductAdditionalInformationV2AdditionalInformationUris[] | null;
  /**
   * An array of additional fees, pricing, discounts, exemptions and bonuses for the product, if applicable. To be treated as secondary documents to the `feesAndPricingUri`. Only to be used if there is a primary `feesAndPricingUri`.
   */
  additionalFeesAndPricingUris?: BankingProductAdditionalInformationV2AdditionalInformationUris[] | null;
  /**
   * An array of additional general overviews for the product or features of the product, if applicable. To be treated as secondary documents to the `overviewUri`. Only to be used if there is a primary `overviewUri`.
   */
  additionalOverviewUris?: BankingProductAdditionalInformationV2AdditionalInformationUris[] | null;
  /**
   * An array of additional terms and conditions for the product, if applicable. To be treated as secondary documents to the `termsUri`. Only to be used if there is a primary `termsUri`.
   */
  additionalTermsUris?: BankingProductAdditionalInformationV2AdditionalInformationUris[] | null;
  /**
   * Description of a bundle that this product can be part of. Mandatory if `additionalBundleUris` includes one or more supporting documents.
   */
  bundleUri?: string | null;
  /**
   * Eligibility rules and criteria for the product. Mandatory if `additionalEligibilityUris` includes one or more supporting documents.
   */
  eligibilityUri?: string | null;
  /**
   * Description of fees, pricing, discounts, exemptions and bonuses for the product. Mandatory if `additionalFeesAndPricingUris` includes one or more supporting documents.
   */
  feesAndPricingUri?: string | null;
  /**
   * General overview of the product. Mandatory if `additionalOverviewUris` includes one or more supporting documents.
   */
  overviewUri?: string | null;
  /**
   * Terms and conditions for the product. Mandatory if `additionalTermsUris` includes one or more supporting documents.
   */
  termsUri?: string | null;
  [k: string]: unknown;
};
export type EnergyPlan = EnergyPlan1 &
  ({
    [k: string]: unknown;
  } & {
    [k: string]: unknown;
  } & {
    [k: string]: unknown;
  });
export type Customer = CommonPerson & {
  /**
   * Array is mandatory but may be empty if no phone numbers are held
   */
  phoneNumbers: CommonPhoneNumber[];
  /**
   * May be empty
   */
  emailAddresses: CommonEmailAddress[];
  /**
   * Array is mandatory but may be empty if no valid addresses are held. One and only one address may have the purpose of REGISTERED. Zero or one, and no more than one, record may have the purpose of MAIL. If zero then the REGISTERED address is to be used for mail
   */
  physicalAddresses: (CommonPhysicalAddress & {
    /**
     * Enumeration of values indicating the purpose of the physical address
     */
    purpose: "MAIL" | "OTHER" | "PHYSICAL" | "REGISTERED" | "WORK";
    [k: string]: unknown;
  })[];
  [k: string]: unknown;
};
export type BankAccount = BankingAccount &
  ({
    [k: string]: unknown;
  } & {
    [k: string]: unknown;
  } & {
    [k: string]: unknown;
  });
export type BankTransaction = BankingTransaction & {
  extendedData: {
    /**
     * Label of the originating payer. Mandatory for inbound payment
     */
    payer?: string;
    /**
     * Label of the target PayID.  Mandatory for an outbound payment. The name assigned to the BSB/Account Number or PayID (by the owner of the PayID)
     */
    payee?: string;
    /**
     * Optional extended data specific to transactions originated via NPP
     */
    extensionUType?: "x2p101Payload";
    x2p101Payload?: {
      /**
       * An extended string description. Required if the extensionUType field is `x2p101Payload`
       */
      extendedDescription?: string;
      /**
       * An end to end ID for the payment created at initiation
       */
      endToEndId?: string;
      /**
       * Purpose of the payment.  Format is defined by NPP standards for the x2p1.01 overlay service
       */
      purposeCode?: string;
      [k: string]: unknown;
    };
    /**
     * Identifier of the applicable overlay service. Valid values are: X2P1.01
     */
    service: "X2P1.01";
    [k: string]: unknown;
  };
  [k: string]: unknown;
};
export type BankingTransaction = ({
  [k: string]: unknown;
} & {
  [k: string]: unknown;
}) & {
  /**
   * ID of the account for which transactions are provided
   */
  accountId: string;
  /**
   * The value of the transaction. Negative values mean money was outgoing from the account
   */
  amount: string;
  /**
   * 6 Digit APCA number for the initiating institution. The field is fixed-width and padded with leading zeros if applicable.
   */
  apcaNumber?: string | null;
  /**
   * BPAY Biller Code for the transaction (if available)
   */
  billerCode?: string | null;
  /**
   * Name of the BPAY biller for the transaction (if available)
   */
  billerName?: string | null;
  /**
   * BPAY CRN for the transaction (if available).<br/>Where the CRN contains sensitive information, it should be masked in line with how the Data Holder currently displays account identifiers in their existing online banking channels. If the contents of the CRN match the format of a Credit Card PAN they should be masked according to the rules applicable for MaskedPANString. If the contents are are otherwise sensitive, then it should be masked using the rules applicable for the MaskedAccountString common type.
   */
  crn?: string | null;
  /**
   * The currency for the transaction amount. AUD assumed if not present
   */
  currency?: string | null;
  /**
   * The transaction description as applied by the financial institution
   */
  description: string;
  /**
   * The time the transaction was executed by the originating customer, if available
   */
  executionDateTime?: string | null;
  /**
   * True if extended information is available using the transaction detail end point. False if extended data is not available
   */
  isDetailAvailable: boolean;
  /**
   * The merchant category code (or MCC) for an outgoing payment to a merchant
   */
  merchantCategoryCode?: string | null;
  /**
   * Name of the merchant for an outgoing payment to a merchant
   */
  merchantName?: string | null;
  /**
   * The time the transaction was posted. This field is Mandatory if the transaction has status POSTED.  This is the time that appears on a standard statement
   */
  postingDateTime?: string | null;
  /**
   * The reference for the transaction provided by the originating institution. Empty string if no data provided
   */
  reference: string;
  /**
   * Status of the transaction whether pending or posted. Note that there is currently no provision in the standards to guarantee the ability to correlate a pending transaction with an associated posted transaction
   */
  status: "PENDING" | "POSTED";
  /**
   * A unique ID of the transaction adhering to the standards for ID permanence.  This is mandatory (through hashing if necessary) unless there are specific and justifiable technical reasons why a transaction cannot be uniquely identified for a particular account type. It is mandatory if `isDetailAvailable` is set to true.
   */
  transactionId?: string | null;
  /**
   * The type of the transaction
   */
  type:
    | "DIRECT_DEBIT"
    | "FEE"
    | "INTEREST_CHARGED"
    | "INTEREST_PAID"
    | "OTHER"
    | "PAYMENT"
    | "TRANSFER_INCOMING"
    | "TRANSFER_OUTGOING";
  /**
   * Date and time at which assets become available to the account owner in case of a credit entry, or cease to be available to the account owner in case of a debit transaction entry
   */
  valueDateTime?: string | null;
  [k: string]: unknown;
};
export type BankPayee = BankingPayeeV2 &
  ({
    [k: string]: unknown;
  } & {
    [k: string]: unknown;
  } & {
    [k: string]: unknown;
  } & {
    [k: string]: unknown;
  });
/**
 * The set of payment amounts and destination accounts for this payment accommodating multi-part payments. A single entry indicates a simple payment with one destination account. Must have at least one entry
 */
export type BankingScheduledPaymentSet = (
  | {
      [k: string]: unknown;
    }
  | {
      [k: string]: unknown;
    }
) & {
  /**
   * The amount of the next payment if known. Mandatory unless the isAmountCalculated field is set to true. Must be zero or positive if present
   */
  amount?: string | null;
  /**
   * The currency for the payment. AUD assumed if not present
   */
  currency?: string | null;
  /**
   * Flag indicating whether the amount of the payment is calculated based on the context of the event. For instance a payment to reduce the balance of a credit card to zero. If absent then false is assumed
   */
  isAmountCalculated?: boolean | null;
  to: BankingScheduledPaymentTo;
  [k: string]: unknown;
};
/**
 * Object containing details of the destination of the payment. Used to specify a variety of payment destination types
 */
export type BankingScheduledPaymentTo = ({
  [k: string]: unknown;
} & {
  [k: string]: unknown;
} & {
  [k: string]: unknown;
} & {
  [k: string]: unknown;
} & {
  [k: string]: unknown;
}) & {
  /**
   * Present if toUType is set to accountId. Indicates that the payment is to another account that is accessible under the current consent
   */
  accountId?: string | null;
  biller?: BankingBillerPayee;
  domestic?: BankingDomesticPayee;
  international?: BankingInternationalPayee;
  /**
   * The short display name of the payee as provided by the customer unless toUType is set to payeeId. Where a customer has not provided a nickname, a display name derived by the bank for payee should be provided that is consistent with existing digital banking channels
   */
  nickname?: string | null;
  /**
   * Present if toUType is set to payeeId. Indicates that the payment is to registered payee that can be accessed using the payee end point. If the Bank Payees scope has not been consented to then a payeeId should not be provided and the full payee details should be provided instead
   */
  payeeId?: string | null;
  /**
   * The reference for the transaction, if applicable, that will be provided by the originating institution for the specific payment. If not empty, it overrides the value provided at the BankingScheduledPayment level.
   */
  payeeReference?: string | null;
  /**
   * The type of object provided that specifies the destination of the funds for the payment.
   */
  toUType: "accountId" | "biller" | "domestic" | "international" | "payeeId";
  [k: string]: unknown;
};
export type BankingDomesticPayee = ({
  [k: string]: unknown;
} & {
  [k: string]: unknown;
} & {
  [k: string]: unknown;
}) & {
  account?: BankingDomesticPayeeAccount;
  card?: BankingDomesticPayeeCard;
  payId?: BankingDomesticPayeePayId;
  /**
   * Type of account object included. Valid values are: **account** A standard Australian account defined by BSB/Account Number. **card** A credit or charge card to pay to (note that PANs are masked). **payId** A PayID recognised by NPP
   */
  payeeAccountUType: "account" | "card" | "payId";
  [k: string]: unknown;
};
/**
 * Object containing the detail of the schedule for the payment
 */
export type BankingScheduledPaymentRecurrence = ({
  [k: string]: unknown;
} & {
  [k: string]: unknown;
} & {
  [k: string]: unknown;
} & {
  [k: string]: unknown;
}) & {
  eventBased?: BankingScheduledPaymentRecurrenceEventBased;
  intervalSchedule?: BankingScheduledPaymentRecurrenceIntervalSchedule;
  lastWeekDay?: BankingScheduledPaymentRecurrenceLastWeekday;
  /**
   * The date of the next payment under the recurrence schedule
   */
  nextPaymentDate?: string | null;
  onceOff?: BankingScheduledPaymentRecurrenceOnceOff;
  /**
   * The type of recurrence used to define the schedule
   */
  recurrenceUType: "eventBased" | "intervalSchedule" | "lastWeekDay" | "onceOff";
  [k: string]: unknown;
};
/**
 * A set of data holders, and their associated data, keyed on data holder ID
 */
export type Holders = {
  [k: string]: Holder;
}[];

/**
 * A JSON schema for defining test data files that can be used to seed a mock, or test, implementation of a Data Holder for the Consumer Data Right
 */
export interface ConsumerDataRightTestDataJSONSchema {
  /**
   * The version of the file formatted using semver (without extensions)
   */
  fileVersion: string;
  /**
   * The version of the CDR standards that these tests are validated for.  For formatted using semver (without extensions)
   */
  standardsVersion: string;
  /**
   * A short title of the test data file
   */
  title: string;
  /**
   * An optional description of the test data file to identify its purpose
   */
  description?: string;
  holders?: Holders;
  /**
   * A cache of previously registered clients
   */
  clientCache?: Client[];
  /**
   * A cache of previously loaded recipients from the CDR Register
   */
  registerCache?: Recipient[];
}
/**
 * Data for a single data holder
 *
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^[a-zA-Z0-9]+$".
 */
export interface Holder {
  /**
   * Unauthenticated data for a single data holder
   */
  unauthenticated: {
    /**
     * Unauthenticated banking data
     */
    banking?: {
      /**
       * An array of banking products
       */
      products?: BankProduct[];
    };
    /**
     * Unauthenticated energy data
     */
    energy?: {
      /**
       * An array of energy plans
       */
      plans?: EnergyPlan[];
    };
    /**
     * Current system status
     */
    admin?: {
      status?: AdminStatus;
      /**
       * An array of planned outages
       */
      outages?: AdminOutage[];
    };
  };
  /**
   * Authenticated data for a single data holder
   */
  authenticated: {
    /**
     * An array of customers and their data
     */
    customers?: CustomerWrapper[];
  };
}
export interface BankingProductV4 {
  additionalInformation?: null | BankingProductAdditionalInformationV2;
  /**
   * A link to an application web page where this product can be applied for.
   */
  applicationUri?: string | null;
  /**
   * A label of the brand for the product. Able to be used for filtering. For data holders with single brands this value is still required
   */
  brand: string;
  /**
   * An optional display name of the brand
   */
  brandName?: string | null;
  /**
   * An array of card art images
   */
  cardArt?:
    | {
        /**
         * URI reference to a PNG, JPG or GIF image with proportions defined by ISO 7810 ID-1 and width no greater than 512 pixels. The URI reference may be a link or url-encoded data URI according to **[[RFC2397]](#nref-RFC2397)**
         */
        imageUri: string;
        /**
         * Display label for the specific image
         */
        title?: string | null;
        [k: string]: unknown;
      }[]
    | null;
  /**
   * A description of the product
   */
  description: string;
  /**
   * The date and time from which this product is effective (ie. is available for origination).  Used to enable the articulation of products to the regime before they are available for customers to originate
   */
  effectiveFrom?: string | null;
  /**
   * The date and time at which this product will be retired and will no longer be offered.  Used to enable the managed deprecation of products
   */
  effectiveTo?: string | null;
  /**
   * Indicates whether the product is specifically tailored to a circumstance.  In this case fees and prices are significantly negotiated depending on context. While all products are open to a degree of tailoring this flag indicates that tailoring is expected and thus that the provision of specific fees and rates is not applicable
   */
  isTailored: boolean;
  /**
   * The last date and time that the information for this product was changed (or the creation date for the product if it has never been altered)
   */
  lastUpdated: string;
  /**
   * The display name of the product
   */
  name: string;
  /**
   * The category to which a product or account belongs. See [here](#product-categories) for more details
   */
  productCategory:
    | "BUSINESS_LOANS"
    | "CRED_AND_CHRG_CARDS"
    | "LEASES"
    | "MARGIN_LOANS"
    | "OVERDRAFTS"
    | "PERS_LOANS"
    | "REGULATED_TRUST_ACCOUNTS"
    | "RESIDENTIAL_MORTGAGES"
    | "TERM_DEPOSITS"
    | "TRADE_FINANCE"
    | "TRANS_AND_SAVINGS_ACCOUNTS"
    | "TRAVEL_CARDS";
  /**
   * A data holder specific unique identifier for this product. This identifier must be unique to a product but does not otherwise need to adhere to ID permanence guidelines.
   */
  productId: string;
  [k: string]: unknown;
}
export interface BankingProductAdditionalInformationV2AdditionalInformationUris {
  /**
   * The URI describing the additional information
   */
  additionalInfoUri: string;
  /**
   * Display text providing more information about the document URI
   */
  description?: string | null;
  [k: string]: unknown;
}
export interface BankingProductBundle {
  /**
   * Display text providing more information on the bundle
   */
  additionalInfo?: string | null;
  /**
   * Link to a web page with more information on the bundle criteria and benefits
   */
  additionalInfoUri?: string | null;
  /**
   * Description of the bundle
   */
  description: string;
  /**
   * Name of the bundle
   */
  name: string;
  /**
   * Array of product IDs for products included in the bundle that are available via the product end points.  Note that this array is not intended to represent a comprehensive model of the products included in the bundle and some products available for the bundle may not be available via the product reference end points
   */
  productIds?: string[] | null;
  [k: string]: unknown;
}
export interface BankingProductFeatureV2 {
  /**
   * Display text providing more information on the feature. Mandatory if the [feature type](#tocSproductfeaturetypedoc) is set to OTHER
   */
  additionalInfo?: string | null;
  /**
   * Link to a web page with more information on this feature
   */
  additionalInfoUri?: string | null;
  /**
   * Generic field containing additional information relevant to the [featureType](#tocSproductfeaturetypedoc) specified. Whether mandatory or not is dependent on the value of the [featureType.](#tocSproductfeaturetypedoc)
   */
  additionalValue?: string | null;
  /**
   * The type of feature described
   */
  featureType:
    | "ADDITIONAL_CARDS"
    | "BALANCE_TRANSFERS"
    | "BILL_PAYMENT"
    | "BONUS_REWARDS"
    | "CARD_ACCESS"
    | "CASHBACK_OFFER"
    | "COMPLEMENTARY_PRODUCT_DISCOUNTS"
    | "DIGITAL_BANKING"
    | "DIGITAL_WALLET"
    | "DONATE_INTEREST"
    | "EXTRA_REPAYMENTS"
    | "FRAUD_PROTECTION"
    | "FREE_TXNS"
    | "FREE_TXNS_ALLOWANCE"
    | "GUARANTOR"
    | "INSURANCE"
    | "INSTALMENT_PLAN"
    | "INTEREST_FREE"
    | "INTEREST_FREE_TRANSFERS"
    | "LOYALTY_PROGRAM"
    | "NOTIFICATIONS"
    | "NPP_ENABLED"
    | "NPP_PAYID"
    | "OFFSET"
    | "OTHER"
    | "OVERDRAFT"
    | "REDRAW"
    | "RELATIONSHIP_MANAGEMENT"
    | "UNLIMITED_TXNS";
  [k: string]: unknown;
}
export interface BankingProductConstraint {
  /**
   * Display text providing more information the constraint
   */
  additionalInfo?: string | null;
  /**
   * Link to a web page with more information on the constraint
   */
  additionalInfoUri?: string | null;
  /**
   * Generic field containing additional information relevant to the [constraintType](#tocSproductconstrainttypedoc) specified.  Whether mandatory or not is dependent on the value of [constraintType](#tocSproductconstrainttypedoc)
   */
  additionalValue?: string | null;
  /**
   * The type of constraint described.  See the next section for an overview of valid values and their meaning
   */
  constraintType: "MAX_BALANCE" | "MAX_LIMIT" | "MIN_BALANCE" | "MIN_LIMIT" | "OPENING_BALANCE";
  [k: string]: unknown;
}
export interface BankingProductEligibility {
  /**
   * Display text providing more information on the [eligibility](#tocSproducteligibilitytypedoc) criteria. Mandatory if the field is set to OTHER
   */
  additionalInfo?: string | null;
  /**
   * Link to a web page with more information on this eligibility criteria
   */
  additionalInfoUri?: string | null;
  /**
   * Generic field containing additional information relevant to the [eligibilityType](#tocSproducteligibilitytypedoc) specified. Whether mandatory or not is dependent on the value of [eligibilityType](#tocSproducteligibilitytypedoc)
   */
  additionalValue?: string | null;
  /**
   * The type of eligibility criteria described.  See the next section for an overview of valid values and their meaning
   */
  eligibilityType:
    | "BUSINESS"
    | "EMPLOYMENT_STATUS"
    | "MAX_AGE"
    | "MIN_AGE"
    | "MIN_INCOME"
    | "MIN_TURNOVER"
    | "NATURAL_PERSON"
    | "OTHER"
    | "PENSION_RECIPIENT"
    | "RESIDENCY_STATUS"
    | "STAFF"
    | "STUDENT";
  [k: string]: unknown;
}
export interface BankingProductFee {
  /**
   * The indicative frequency with which the fee is calculated on the account. Only applies if balanceRate or accruedRate is also present. Formatted according to [ISO 8601 Durations](https://en.wikipedia.org/wiki/ISO_8601#Durations) (excludes recurrence syntax)
   */
  accrualFrequency?: string | null;
  /**
   * A fee rate calculated based on a proportion of the calculated interest accrued on the account. One of amount, balanceRate, transactionRate and accruedRate is mandatory unless the *feeType* "VARIABLE" is supplied
   */
  accruedRate?: string | null;
  /**
   * Display text providing more information on the fee
   */
  additionalInfo?: string | null;
  /**
   * Link to a web page with more information on this fee
   */
  additionalInfoUri?: string | null;
  /**
   * Generic field containing additional information relevant to the [feeType](#tocSproductfeetypedoc) specified. Whether mandatory or not is dependent on the value of [feeType](#tocSproductfeetypedoc)
   */
  additionalValue?: string | null;
  /**
   * The amount charged for the fee. One of amount, balanceRate, transactionRate and accruedRate is mandatory unless the *feeType* "VARIABLE" is supplied
   */
  amount?: string | null;
  /**
   * A fee rate calculated based on a proportion of the balance. One of amount, balanceRate, transactionRate and accruedRate is mandatory unless the *feeType* "VARIABLE" is supplied.
   */
  balanceRate?: string | null;
  /**
   * The currency the fee will be charged in. Assumes AUD if absent
   */
  currency?: string | null;
  /**
   * An optional list of discounts to this fee that may be available
   */
  discounts?: BankingProductDiscount[] | null;
  /**
   * The type of fee
   */
  feeType:
    | "DEPOSIT"
    | "EVENT"
    | "EXIT"
    | "PAYMENT"
    | "PERIODIC"
    | "PURCHASE"
    | "TRANSACTION"
    | "UPFRONT"
    | "VARIABLE"
    | "WITHDRAWAL";
  /**
   * Name of the fee
   */
  name: string;
  /**
   * A fee rate calculated based on a proportion of a transaction. One of amount, balanceRate, transactionRate and accruedRate is mandatory unless the *feeType* "VARIABLE" is supplied
   */
  transactionRate?: string | null;
  [k: string]: unknown;
}
export interface BankingProductDiscount {
  /**
   * A discount rate calculated based on a proportion of the calculated interest accrued on the account. Note that the currency of the fee discount is expected to be the same as the currency of the fee itself. One of amount, balanceRate, transactionRate, accruedRate and feeRate is mandatory. Unless noted in additionalInfo, assumes the application and calculation frequency are the same as the corresponding fee
   */
  accruedRate?: string | null;
  /**
   * Display text providing more information on the discount
   */
  additionalInfo?: string | null;
  /**
   * Link to a web page with more information on this discount
   */
  additionalInfoUri?: string | null;
  /**
   * Generic field containing additional information relevant to the [discountType](#tocSproductdiscounttypedoc) specified. Whether mandatory or not is dependent on the value of [discountType](#tocSproductdiscounttypedoc)
   */
  additionalValue?: string | null;
  /**
   * Dollar value of the discount. One of amount, balanceRate, transactionRate, accruedRate and feeRate is mandatory.
   */
  amount?: string | null;
  /**
   * A discount rate calculated based on a proportion of the balance. Note that the currency of the fee discount is expected to be the same as the currency of the fee itself. One of amount, balanceRate, transactionRate, accruedRate and feeRate is mandatory. Unless noted in additionalInfo, assumes the application and calculation frequency are the same as the corresponding fee
   */
  balanceRate?: string | null;
  /**
   * Description of the discount
   */
  description: string;
  /**
   * The type of discount. See the next section for an overview of valid values and their meaning
   */
  discountType: "BALANCE" | "DEPOSITS" | "ELIGIBILITY_ONLY" | "FEE_CAP" | "PAYMENTS";
  /**
   * Eligibility constraints that apply to this discount. Mandatory if ``discountType`` is ``ELIGIBILITY_ONLY``.
   */
  eligibility?: BankingProductDiscountEligibility[] | null;
  /**
   * A discount rate calculated based on a proportion of the fee to which this discount is attached. Note that the currency of the fee discount is expected to be the same as the currency of the fee itself. One of amount, balanceRate, transactionRate, accruedRate and feeRate is mandatory. Unless noted in additionalInfo, assumes the application and calculation frequency are the same as the corresponding fee
   */
  feeRate?: string | null;
  /**
   * A discount rate calculated based on a proportion of a transaction. Note that the currency of the fee discount is expected to be the same as the currency of the fee itself. One of amount, balanceRate, transactionRate, accruedRate and feeRate is mandatory
   */
  transactionRate?: string | null;
  [k: string]: unknown;
}
export interface BankingProductDiscountEligibility {
  /**
   * Display text providing more information on this eligibility constraint. Whether mandatory or not is dependent on the value of [discountEligibilityType](#tocSproductdiscounteligibilitydoc)
   */
  additionalInfo?: string | null;
  /**
   * Link to a web page with more information on this eligibility constraint
   */
  additionalInfoUri?: string | null;
  /**
   * Generic field containing additional information relevant to the [discountEligibilityType](#tocSproductdiscounteligibilitydoc) specified. Whether mandatory or not is dependent on the value of [discountEligibilityType](#tocSproductdiscounteligibilitydoc)
   */
  additionalValue?: string | null;
  /**
   * The type of the specific eligibility constraint for a discount
   */
  discountEligibilityType:
    | "BUSINESS"
    | "EMPLOYMENT_STATUS"
    | "INTRODUCTORY"
    | "MAX_AGE"
    | "MIN_AGE"
    | "MIN_INCOME"
    | "MIN_TURNOVER"
    | "NATURAL_PERSON"
    | "OTHER"
    | "PENSION_RECIPIENT"
    | "RESIDENCY_STATUS"
    | "STAFF"
    | "STUDENT";
  [k: string]: unknown;
}
export interface BankingProductDepositRate {
  /**
   * Display text providing more information on the rate
   */
  additionalInfo?: string | null;
  /**
   * Link to a web page with more information on this rate
   */
  additionalInfoUri?: string | null;
  /**
   * Generic field containing additional information relevant to the [depositRateType](#tocSproductdepositratetypedoc) specified. Whether mandatory or not is dependent on the value of [depositRateType](#tocSproductdepositratetypedoc)
   */
  additionalValue?: string | null;
  /**
   * The period after which the calculated amount(s) (see calculationFrequency) are 'applied' (i.e. debited or credited) to the account. Formatted according to [ISO 8601 Durations](https://en.wikipedia.org/wiki/ISO_8601#Durations) (excludes recurrence syntax)
   */
  applicationFrequency?: string | null;
  /**
   * The period after which the rate is applied to the balance to calculate the amount due for the period. Calculation of the amount is often daily (as balances may change) but accumulated until the total amount is 'applied' to the account (see applicationFrequency). Formatted according to [ISO 8601 Durations](https://en.wikipedia.org/wiki/ISO_8601#Durations) (excludes recurrence syntax)
   */
  calculationFrequency?: string | null;
  /**
   * The type of rate (base, bonus, etc). See the next section for an overview of valid values and their meaning
   */
  depositRateType: "BONUS" | "BUNDLE_BONUS" | "FIXED" | "FLOATING" | "INTRODUCTORY" | "MARKET_LINKED" | "VARIABLE";
  /**
   * The rate to be applied
   */
  rate: string;
  /**
   * Rate tiers applicable for this rate
   */
  tiers?: BankingProductRateTierV3[] | null;
  [k: string]: unknown;
}
/**
 * Defines the criteria and conditions for which a rate applies
 */
export interface BankingProductRateTierV3 {
  /**
   * Display text providing more information on the rate tier.
   */
  additionalInfo?: string | null;
  /**
   * Link to a web page with more information on this rate tier
   */
  additionalInfoUri?: string | null;
  applicabilityConditions?: null | BankingProductRateCondition;
  /**
   * The number of tierUnitOfMeasure units that form the upper bound of the tier or band. For a tier with a discrete value (as opposed to a range of values e.g. 1 month) this must be the same as tierValueMinimum. Where this is the same as the tierValueMinimum value of the next-higher tier the referenced tier should be exclusive of this value. For example a term deposit of 2 months falls into the upper tier of the following tiers: (1 – 2 months, 2 – 3 months). If absent the tier's range has no upper bound.
   */
  maximumValue?: number | null;
  /**
   * The number of tierUnitOfMeasure units that form the lower bound of the tier. The tier should be inclusive of this value
   */
  minimumValue: number;
  /**
   * A display name for the tier
   */
  name: string;
  /**
   * The method used to calculate the amount to be applied using one or more tiers. A single rate may be applied to the entire balance or each applicable tier rate is applied to the portion of the balance that falls into that tier (referred to as 'bands' or 'steps')
   */
  rateApplicationMethod?: ("PER_TIER" | "WHOLE_BALANCE") | null;
  /**
   * The unit of measure that applies to the tierValueMinimum and tierValueMaximum values e.g. a **DOLLAR** amount. **PERCENT** (in the case of loan-to-value ratio or LVR). Tier term period representing a discrete number of **MONTH**'s or **DAY**'s (in the case of term deposit tiers)
   */
  unitOfMeasure: "DAY" | "DOLLAR" | "MONTH" | "PERCENT";
  [k: string]: unknown;
}
/**
 * Defines a condition for the applicability of a tiered rate
 */
export interface BankingProductRateCondition {
  /**
   * Display text providing more information on the condition
   */
  additionalInfo?: string | null;
  /**
   * Link to a web page with more information on this condition
   */
  additionalInfoUri?: string | null;
  [k: string]: unknown;
}
export interface BankingProductLendingRateV2 {
  /**
   * Display text providing more information on the rate.
   */
  additionalInfo?: string | null;
  /**
   * Link to a web page with more information on this rate
   */
  additionalInfoUri?: string | null;
  /**
   * Generic field containing additional information relevant to the [lendingRateType](#tocSproductlendingratetypedoc) specified. Whether mandatory or not is dependent on the value of [lendingRateType](#tocSproductlendingratetypedoc)
   */
  additionalValue?: string | null;
  /**
   * The period after which the calculated amount(s) (see calculationFrequency) are 'applied' (i.e. debited or credited) to the account. Formatted according to [ISO 8601 Durations](https://en.wikipedia.org/wiki/ISO_8601#Durations) (excludes recurrence syntax)
   */
  applicationFrequency?: string | null;
  /**
   * The period after which the rate is applied to the balance to calculate the amount due for the period. Calculation of the amount is often daily (as balances may change) but accumulated until the total amount is 'applied' to the account (see applicationFrequency). Formatted according to [ISO 8601 Durations](https://en.wikipedia.org/wiki/ISO_8601#Durations) (excludes recurrence syntax)
   */
  calculationFrequency?: string | null;
  /**
   * A comparison rate equivalent for this rate
   */
  comparisonRate?: string | null;
  /**
   * When loan payments are due to be paid within each period. The investment benefit of earlier payments affect the rate that can be offered
   */
  interestPaymentDue?: ("IN_ADVANCE" | "IN_ARREARS") | null;
  /**
   * The type of rate (fixed, variable, etc). See the next section for an overview of valid values and their meaning
   */
  lendingRateType:
    | "BUNDLE_DISCOUNT_FIXED"
    | "BUNDLE_DISCOUNT_VARIABLE"
    | "CASH_ADVANCE"
    | "DISCOUNT"
    | "FIXED"
    | "FLOATING"
    | "INTRODUCTORY"
    | "MARKET_LINKED"
    | "PENALTY"
    | "PURCHASE"
    | "VARIABLE";
  /**
   * The reason for taking out the loan. If absent, the lending rate is applicable to all loan purposes
   */
  loanPurpose?: ("INVESTMENT" | "OWNER_OCCUPIED") | null;
  /**
   * The rate to be applied
   */
  rate: string;
  /**
   * Options in place for repayments. If absent, the lending rate is applicable to all repayment types
   */
  repaymentType?: ("INTEREST_ONLY" | "PRINCIPAL_AND_INTEREST") | null;
  /**
   * Rate tiers applicable for this rate
   */
  tiers?: BankingProductRateTierV3[] | null;
  [k: string]: unknown;
}
export interface EnergyPlan1 {
  /**
   * Object that contains links to additional information on specific topics
   */
  additionalInformation?: {
    /**
     * A link to detail on bundles that this plan can be a part of
     */
    bundleUri?: string | null;
    /**
     * A link to detail on eligibility criteria for the plan
     */
    eligibilityUri?: string | null;
    /**
     * A link to a general overview of the plan
     */
    overviewUri?: string | null;
    /**
     * A link to detail on pricing for the plan
     */
    pricingUri?: string | null;
    /**
     * A link to terms and conditions for the plan
     */
    termsUri?: string | null;
    [k: string]: unknown;
  } | null;
  /**
   * A link to an application web page where this plan can be applied for
   */
  applicationUri?: string | null;
  /**
   * The ID of the brand under which this plan is offered
   */
  brand: string;
  /**
   * The display name of the brand under which this plan is offered
   */
  brandName: string;
  /**
   * The type of customer that the plan is offered to.  If absent then the plan is available to all customers
   */
  customerType?: ("RESIDENTIAL" | "BUSINESS") | null;
  /**
   * A description of the plan
   */
  description?: string | null;
  /**
   * The display name of the plan
   */
  displayName?: string | null;
  /**
   * The date and time from which this plan is effective (ie. is available for origination). Used to enable the articulation of products to the regime before they are available for customers to originate
   */
  effectiveFrom?: string | null;
  /**
   * The date and time at which this plan will be retired and will no longer be offered. Used to enable the managed deprecation of plans
   */
  effectiveTo?: string | null;
  /**
   * The fuel types covered by the plan
   */
  fuelType: "ELECTRICITY" | "GAS" | "DUAL";
  /**
   * Describes the geographical area that the plan is available for.  If absent then it is assumed the plan is not geographically limited
   */
  geography?: {
    /**
     * Array of distributors for the plan. Must have at least one entry
     */
    distributors: string[];
    /**
     * Array of valid Australian post codes that are specifically excluded from the plan.  Each element is a single four digit postcode (e.g. 3000) or a range of postcodes defined by two four digit postcodes and a hyphen (e.g. 3000-3999)
     */
    excludedPostcodes?: string[] | null;
    /**
     * Array of valid Australian post codes that are included from the plan.  If absent defaults to all non-excluded post codes.  Each element is a single four digit postcode (e.g. 3000) or a range of postcodes defined by two four digit postcodes and a hyphen (e.g. 3000-3999)
     */
    includedPostcodes?: string[] | null;
    [k: string]: unknown;
  } | null;
  /**
   * The last date and time that the information for this plan was changed (or the creation date for the plan if it has never been altered)
   */
  lastUpdated: string;
  /**
   * The ID of the specific plan
   */
  planId: string;
  /**
   * The type of the plan
   */
  type: "STANDING" | "MARKET" | "REGULATED";
  [k: string]: unknown;
}
/**
 * A status object for the holder
 */
export interface AdminStatus {
  [k: string]: unknown;
}
/**
 * A planned outage object for the holder
 */
export interface AdminOutage {
  [k: string]: unknown;
}
/**
 * A wrapper for a single customer to contain all of the data related to the customer
 */
export interface CustomerWrapper {
  customer: Customer;
  /**
   * Banking data for this customer
   */
  banking: {
    /**
     * An array of accounts and their
     */
    accounts?: BankAccountWrapper[];
    /**
     * An array of direct debit authorisations
     */
    directDebits?: BankingDirectDebit[];
    /**
     * An array of payees
     */
    payees?: BankPayee[];
    /**
     * An array of payment schedules
     */
    payments?: BankingScheduledPayment[];
    [k: string]: unknown;
  };
}
export interface CommonPerson {
  /**
   * For people with single names this field need not be present. The single name should be in the lastName field. Where a data holder cannot determine first and middle names from a collection of given names, a single string representing all given names MAY be provided.
   */
  firstName?: string | null;
  /**
   * For people with single names the single name should be in this field
   */
  lastName: string;
  /**
   * The date and time that this record was last updated by the customer.  If no update has occurred then this date should reflect the initial creation date for the data
   */
  lastUpdateTime?: string | null;
  /**
   * Field is mandatory but array may be empty
   */
  middleNames: string[];
  /**
   * Value is a valid **[[ANZSCO]](#iref-ANZSCO)** Standard Occupation classification code. If the occupation code held by the data holder is not one of the supported **[[ANZSCO]](#iref-ANZSCO)** versions, then it must not be supplied.
   */
  occupationCode?: string | null;
  /**
   * The applicable **[[ANZSCO]](#iref-ANZSCO)** release version of the occupation code provided. Mandatory if an ``occupationCode`` is supplied. If ``occupationCode`` is supplied but ``occupationCodeVersion`` is absent, default is ``ANZSCO_1220.0_2013_V1.2``
   */
  occupationCodeVersion?:
    | ("ANZSCO_1220.0_2006_V1.0" | "ANZSCO_1220.0_2006_V1.1" | "ANZSCO_1220.0_2013_V1.2" | "ANZSCO_1220.0_2013_V1.3")
    | null;
  /**
   * Also known as title or salutation.  The prefix to the name (e.g. Mr, Mrs, Ms, Miss, Sir, etc)
   */
  prefix?: string | null;
  /**
   * Used for a trailing suffix to the name (e.g. Jr)
   */
  suffix?: string | null;
  [k: string]: unknown;
}
export interface CommonPhoneNumber {
  /**
   * Required for non Mobile Phones, if field is present and refers to Australian code - the leading 0 should be omitted.
   */
  areaCode?: string | null;
  /**
   * If absent, assumed to be Australia (+61). The + should be included
   */
  countryCode?: string | null;
  /**
   * An extension number (if applicable)
   */
  extension?: string | null;
  /**
   * Fully formatted phone number with country code, area code, number and extension incorporated. Formatted according to section 5.1.4. of **[[RFC3966]](#iref-RFC3966)**
   */
  fullNumber: string;
  /**
   * May be true for one and only one entry to indicate the preferred phone number. Assumed to be 'false' if not present
   */
  isPreferred?: boolean | null;
  /**
   * The actual phone number, with leading zeros as appropriate
   */
  number: string;
  /**
   * The purpose of the number as specified by the customer
   */
  purpose: "HOME" | "INTERNATIONAL" | "MOBILE" | "OTHER" | "UNSPECIFIED" | "WORK";
  [k: string]: unknown;
}
export interface CommonEmailAddress {
  /**
   * A correctly formatted email address, as defined by the addr-spec format in **[[RFC5322]](#nref-RFC5322)**
   */
  address: string;
  /**
   * May be true for one and only one email record in the collection. Denotes the default email address
   */
  isPreferred?: boolean | null;
  /**
   * The purpose for the email, as specified by the customer (Enumeration)
   */
  purpose: "HOME" | "OTHER" | "UNSPECIFIED" | "WORK";
  [k: string]: unknown;
}
export interface CommonPhysicalAddress {
  /**
   * The type of address object present
   */
  addressUType: "paf" | "simple";
  paf?: CommonPAFAddress;
  simple?: CommonSimpleAddress;
  [k: string]: unknown;
}
/**
 * Australian address formatted according to the file format defined by the [PAF file format](https://auspost.com.au/content/dam/auspost_corp/media/documents/australia-post-data-guide.pdf)
 */
export interface CommonPAFAddress {
  /**
   * Building/Property name 1
   */
  buildingName1?: string | null;
  /**
   * Building/Property name 2
   */
  buildingName2?: string | null;
  /**
   * Unique identifier for an address as defined by Australia Post.  Also known as Delivery Point Identifier
   */
  dpid?: string | null;
  /**
   * Unit number (including suffix, if applicable)
   */
  flatUnitNumber?: string | null;
  /**
   * Type of flat or unit for the address
   */
  flatUnitType?: string | null;
  /**
   * Floor or level number (including alpha characters)
   */
  floorLevelNumber?: string | null;
  /**
   * Type of floor or level for the address
   */
  floorLevelType?: string | null;
  /**
   * Full name of locality
   */
  localityName: string;
  /**
   * Allotment number for the address
   */
  lotNumber?: string | null;
  /**
   * Postal delivery number if the address is a postal delivery type
   */
  postalDeliveryNumber?: number | null;
  /**
   * Postal delivery number prefix related to the postal delivery number
   */
  postalDeliveryNumberPrefix?: string | null;
  /**
   * Postal delivery number suffix related to the postal delivery number
   */
  postalDeliveryNumberSuffix?: string | null;
  /**
   * Postal delivery type. (eg. PO BOX). Valid enumeration defined by Australia Post PAF code file
   */
  postalDeliveryType?: string | null;
  /**
   * Postcode for the locality
   */
  postcode: string;
  /**
   * State in which the address belongs. Valid enumeration defined by Australia Post PAF code file [State Type Abbreviation](https://auspost.com.au/content/dam/auspost_corp/media/documents/australia-post-data-guide.pdf). NSW, QLD, VIC, NT, WA, SA, TAS, ACT, AAT
   */
  state: string;
  /**
   * The name of the street
   */
  streetName?: string | null;
  /**
   * The street type suffix. Valid enumeration defined by Australia Post PAF code file
   */
  streetSuffix?: string | null;
  /**
   * The street type. Valid enumeration defined by Australia Post PAF code file
   */
  streetType?: string | null;
  /**
   * Thoroughfare number for a property (first number in a property ranged address)
   */
  thoroughfareNumber1?: number | null;
  /**
   * Suffix for the thoroughfare number. Only relevant is thoroughfareNumber1 is populated
   */
  thoroughfareNumber1Suffix?: string | null;
  /**
   * Second thoroughfare number (only used if the property has a ranged address eg 23-25)
   */
  thoroughfareNumber2?: number | null;
  /**
   * Suffix for the second thoroughfare number. Only relevant is thoroughfareNumber2 is populated
   */
  thoroughfareNumber2Suffix?: string | null;
  [k: string]: unknown;
}
export interface CommonSimpleAddress {
  /**
   * First line of the standard address object
   */
  addressLine1: string;
  /**
   * Second line of the standard address object
   */
  addressLine2?: string | null;
  /**
   * Third line of the standard address object
   */
  addressLine3?: string | null;
  /**
   * Name of the city or locality
   */
  city: string;
  /**
   * A valid [ISO 3166 Alpha-3](https://www.iso.org/iso-3166-country-codes.html) country code. Australia (AUS) is assumed if country is not present.
   */
  country?: string | null;
  /**
   * Name of the individual or business formatted for inclusion in an address used for physical mail
   */
  mailingName?: string | null;
  /**
   * Mandatory for Australian addresses
   */
  postcode?: string | null;
  /**
   * Free text if the country is not Australia. If country is Australia then must be one of the values defined by the [State Type Abbreviation](https://auspost.com.au/content/dam/auspost_corp/media/documents/australia-post-data-guide.pdf) in the PAF file format. NSW, QLD, VIC, NT, WA, SA, TAS, ACT, AAT
   */
  state: string;
  [k: string]: unknown;
}
/**
 * A wrapper for a single bank account to contain all of the data related to the account
 */
export interface BankAccountWrapper {
  account: BankAccount;
  balance: BankingBalance;
  /**
   * An array of transactions for the account
   */
  transactions?: BankTransaction[];
}
export interface BankingAccount {
  /**
   * A unique ID of the account adhering to the standards for ID permanence
   */
  accountId: string;
  /**
   * Date that the account was created (if known)
   */
  creationDate?: string | null;
  /**
   * The display name of the account as defined by the bank. This should not incorporate account numbers or PANs. If it does the values should be masked according to the rules of the MaskedAccountString common type.
   */
  displayName: string;
  /**
   * Flag indicating that the customer associated with the authorisation is an owner of the account. Does not indicate sole ownership, however. If not present then 'true' is assumed
   */
  isOwned?: boolean | null;
  /**
   * A masked version of the account. Whether BSB/Account Number, Credit Card PAN or another number
   */
  maskedNumber: string;
  /**
   * A customer supplied nick name for the account
   */
  nickname?: string | null;
  /**
   * Open or closed status for the account. If not present then OPEN is assumed
   */
  openStatus?: ("CLOSED" | "OPEN") | null;
  /**
   * The category to which a product or account belongs. See [here](#product-categories) for more details
   */
  productCategory:
    | "BUSINESS_LOANS"
    | "CRED_AND_CHRG_CARDS"
    | "LEASES"
    | "MARGIN_LOANS"
    | "OVERDRAFTS"
    | "PERS_LOANS"
    | "REGULATED_TRUST_ACCOUNTS"
    | "RESIDENTIAL_MORTGAGES"
    | "TERM_DEPOSITS"
    | "TRADE_FINANCE"
    | "TRANS_AND_SAVINGS_ACCOUNTS"
    | "TRAVEL_CARDS";
  /**
   * The unique identifier of the account as defined by the data holder (akin to model number for the account)
   */
  productName: string;
  [k: string]: unknown;
}
export interface BankingBalance {
  /**
   * A unique ID of the account adhering to the standards for ID permanence
   */
  accountId: string;
  /**
   * Object representing the available limit amortised according to payment schedule. Assumed to be zero if absent
   */
  amortisedLimit?: string | null;
  /**
   * Balance representing the amount of funds available for transfer. Assumed to be zero or positive
   */
  availableBalance: string;
  /**
   * Object representing the maximum amount of credit that is available for this account. Assumed to be zero if absent
   */
  creditLimit?: string | null;
  /**
   * The currency for the balance amounts. If absent assumed to be AUD
   */
  currency?: string | null;
  /**
   * The balance of the account at this time. Should align to the balance available via other channels such as Internet Banking. Assumed to be negative if the customer has money owing
   */
  currentBalance: string;
  /**
   * Optional array of balances for the account in other currencies. Included to support accounts that support multi-currency purses such as Travel Cards
   */
  purses?: BankingBalancePurse[] | null;
  [k: string]: unknown;
}
export interface BankingBalancePurse {
  /**
   * The balance available for this additional currency purse
   */
  amount: string;
  /**
   * The currency for the purse
   */
  currency?: string | null;
  [k: string]: unknown;
}
export interface BankingDirectDebit {
  /**
   * A unique ID of the account adhering to the standards for ID permanence.
   */
  accountId: string;
  authorisedEntity: BankingAuthorisedEntity;
  /**
   * The amount of the last debit executed under this authorisation
   */
  lastDebitAmount?: string | null;
  /**
   * The date and time of the last debit executed under this authorisation
   */
  lastDebitDateTime?: string | null;
  [k: string]: unknown;
}
export interface BankingAuthorisedEntity {
  /**
   * Australian Business Number for the authorised entity
   */
  abn?: string | null;
  /**
   * Australian Company Number for the authorised entity
   */
  acn?: string | null;
  /**
   * Australian Registered Body Number for the authorised entity
   */
  arbn?: string | null;
  /**
   * Description of the authorised entity derived from previously executed direct debits
   */
  description?: string | null;
  /**
   * Name of the financial institution through which the direct debit will be executed. Is required unless the payment is made via a credit card scheme
   */
  financialInstitution?: string | null;
  [k: string]: unknown;
}
export interface BankingPayeeV2 {
  /**
   * The date the payee was created by the customer
   */
  creationDate?: string | null;
  /**
   * A description of the payee provided by the customer
   */
  description?: string | null;
  /**
   * The short display name of the payee as provided by the customer. Where a customer has not provided a nickname, a display name derived by the bank for the payee consistent with existing digital banking channels
   */
  nickname: string;
  /**
   * ID of the payee adhering to the rules of ID permanence
   */
  payeeId: string;
  /**
   * The type of payee.<br/>DOMESTIC means a registered payee for domestic payments including NPP. <br/>INTERNATIONAL means a registered payee for international payments. <br/>BILLER means a registered payee for BPAY. <br/>DIGITAL_WALLET means a registered payee for a bank's digital wallet
   */
  type: "BILLER" | "DIGITAL_WALLET" | "DOMESTIC" | "INTERNATIONAL";
  [k: string]: unknown;
}
export interface BankingScheduledPayment {
  from: BankingScheduledPaymentFrom;
  /**
   * The short display name of the scheduled payment as provided by the customer if provided. Where a customer has not provided a nickname, a display name derived by the bank for the scheduled payment should be provided that is consistent with existing digital banking channels
   */
  nickname?: string | null;
  /**
   * The reference for the transaction, if applicable, that will be provided by the originating institution for all payments in the payment set. Empty string if no data provided
   */
  payeeReference?: string | null;
  /**
   * The reference for the transaction that will be used by the originating institution for the purposes of constructing a statement narrative on the payer’s account. Empty string if no data provided
   */
  payerReference: string;
  paymentSet: BankingScheduledPaymentSet[];
  recurrence: BankingScheduledPaymentRecurrence;
  /**
   * A unique ID of the scheduled payment adhering to the standards for ID permanence
   */
  scheduledPaymentId: string;
  /**
   * Indicates whether the schedule is currently active. The value SKIP is equivalent to ACTIVE except that the customer has requested the next normal occurrence to be skipped.
   */
  status: "ACTIVE" | "INACTIVE" | "SKIP";
  [k: string]: unknown;
}
/**
 * Object containing details of the source of the payment. Currently only specifies an account ID but provided as an object to facilitate future extensibility and consistency with the to object
 */
export interface BankingScheduledPaymentFrom {
  /**
   * ID of the account that is the source of funds for the payment
   */
  accountId: string;
  [k: string]: unknown;
}
export interface BankingBillerPayee {
  /**
   * BPAY Biller Code of the Biller
   */
  billerCode: string;
  /**
   * Name of the Biller
   */
  billerName: string;
  /**
   * BPAY CRN of the Biller (if available).<br/>Where the CRN contains sensitive information, it should be masked in line with how the Data Holder currently displays account identifiers in their existing online banking channels. If the contents of the CRN match the format of a Credit Card PAN they should be masked according to the rules applicable for MaskedPANString. If the contents are are otherwise sensitive, then it should be masked using the rules applicable for the MaskedAccountString common type.
   */
  crn?: string | null;
  [k: string]: unknown;
}
export interface BankingDomesticPayeeAccount {
  /**
   * Name of the account to pay to
   */
  accountName?: string | null;
  /**
   * Number of the account to pay to
   */
  accountNumber: string;
  /**
   * BSB of the account to pay to
   */
  bsb: string;
  [k: string]: unknown;
}
export interface BankingDomesticPayeeCard {
  /**
   * Name of the account to pay to
   */
  cardNumber: string;
  [k: string]: unknown;
}
export interface BankingDomesticPayeePayId {
  /**
   * The identifier of the PayID (dependent on type)
   */
  identifier: string;
  /**
   * The name assigned to the PayID by the owner of the PayID
   */
  name?: string | null;
  /**
   * The type of the PayID
   */
  type: "ABN" | "EMAIL" | "ORG_IDENTIFIER" | "TELEPHONE";
  [k: string]: unknown;
}
export interface BankingInternationalPayee {
  bankDetails: {
    /**
     * Account Targeted for payment
     */
    accountNumber: string;
    bankAddress?: {
      /**
       * Address of the recipient Bank
       */
      address: string;
      /**
       * Name of the recipient Bank
       */
      name: string;
      [k: string]: unknown;
    } | null;
    /**
     * Swift bank code.  Aligns with standard [ISO 9362](https://www.iso.org/standard/60390.html)
     */
    beneficiaryBankBIC?: string | null;
    /**
     * Number for the Clearing House Interbank Payments System
     */
    chipNumber?: string | null;
    /**
     * Country of the recipient institution. A valid [ISO 3166 Alpha-3](https://www.iso.org/iso-3166-country-codes.html) country code
     */
    country: string;
    /**
     * Number for Fedwire payment (Federal Reserve Wire Network)
     */
    fedWireNumber?: string | null;
    /**
     * The legal entity identifier (LEI) for the beneficiary.  Aligns with [ISO 17442](https://www.iso.org/standard/59771.html)
     */
    legalEntityIdentifier?: string | null;
    /**
     * International bank routing number
     */
    routingNumber?: string | null;
    /**
     * Sort code used for account identification in some jurisdictions
     */
    sortCode?: string | null;
    [k: string]: unknown;
  };
  beneficiaryDetails: {
    /**
     * Country where the beneficiary resides. A valid [ISO 3166 Alpha-3](https://www.iso.org/iso-3166-country-codes.html) country code
     */
    country: string;
    /**
     * Response message for the payment
     */
    message?: string | null;
    /**
     * Name of the beneficiary
     */
    name?: string | null;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
/**
 * Indicates that the schedule of payments is defined according to an external event that cannot be predetermined. Mandatory if recurrenceUType is set to eventBased
 */
export interface BankingScheduledPaymentRecurrenceEventBased {
  /**
   * Description of the event and conditions that will result in the payment. Expected to be formatted for display to a customer
   */
  description: string;
  [k: string]: unknown;
}
/**
 * Indicates that the schedule of payments is defined by a series of intervals. Mandatory if recurrenceUType is set to intervalSchedule
 */
export interface BankingScheduledPaymentRecurrenceIntervalSchedule {
  /**
   * The limit date after which no more payments should be made using this schedule. If both finalPaymentDate and paymentsRemaining are present then payments will stop according to the most constraining value. If neither field is present the payments will continue indefinitely
   */
  finalPaymentDate?: string | null;
  /**
   * An array of interval objects defining the payment schedule.  Each entry in the array is additive, in that it adds payments to the overall payment schedule.  If multiple intervals result in a payment on the same day then only one payment will be made. Must have at least one entry
   */
  intervals: BankingScheduledPaymentInterval[];
  /**
   * Enumerated field giving the treatment where a scheduled payment date is not a business day. If absent assumed to be ON.<br/>**AFTER** - If a scheduled payment date is a non-business day the payment will be made on the first business day after the scheduled payment date.<br/>**BEFORE** - If a scheduled payment date is a non-business day the payment will be made on the first business day before the scheduled payment date.<br/>**ON** - If a scheduled payment date is a non-business day the payment will be made on that day regardless.<br/>**ONLY** - Payments only occur on business days. If a scheduled payment date is a non-business day the payment will be ignored
   */
  nonBusinessDayTreatment?: ("AFTER" | "BEFORE" | "ON" | "ONLY") | null;
  /**
   * Indicates the number of payments remaining in the schedule. If both finalPaymentDate and paymentsRemaining are present then payments will stop according to the most constraining value, If neither field is present the payments will continue indefinitely
   */
  paymentsRemaining?: number | null;
  [k: string]: unknown;
}
export interface BankingScheduledPaymentInterval {
  /**
   * Uses an interval to define the ordinal day within the interval defined by the interval field on which the payment occurs. If the resulting duration is 0 days in length or larger than the number of days in the interval then the payment will occur on the last day of the interval. A duration of 1 day indicates the first day of the interval. If absent the assumed value is P1D. Formatted according to [ISO 8601 Durations](https://en.wikipedia.org/wiki/ISO_8601#Durations) (excludes recurrence syntax) with components less than a day in length ignored. The first day of a week is considered to be Monday.
   */
  dayInInterval?: string | null;
  /**
   * An interval for the payment. Formatted according to [ISO 8601 Durations](https://en.wikipedia.org/wiki/ISO_8601#Durations)  (excludes recurrence syntax) with components less than a day in length ignored. This duration defines the period between payments starting with nextPaymentDate
   */
  interval: string;
  [k: string]: unknown;
}
/**
 * Indicates that the schedule of payments is defined according to the last occurrence of a specific weekday in an interval. Mandatory if recurrenceUType is set to lastWeekDay
 */
export interface BankingScheduledPaymentRecurrenceLastWeekday {
  /**
   * The limit date after which no more payments should be made using this schedule. If both finalPaymentDate and paymentsRemaining are present then payments will stop according to the most constraining value. If neither field is present the payments will continue indefinitely
   */
  finalPaymentDate?: string | null;
  /**
   * The interval for the payment. Formatted according to [ISO 8601 Durations](https://en.wikipedia.org/wiki/ISO_8601#Durations) (excludes recurrence syntax) with components less than a day in length ignored. This duration defines the period between payments starting with nextPaymentDate
   */
  interval: string;
  /**
   * The weekDay specified. The payment will occur on the last occurrence of this weekday in the interval.
   */
  lastWeekDay: "FRI" | "MON" | "SAT" | "SUN" | "THU" | "TUE" | "WED";
  /**
   * Enumerated field giving the treatment where a scheduled payment date is not a business day. If absent assumed to be ON.<br/>**AFTER** - If a scheduled payment date is a non-business day the payment will be made on the first business day after the scheduled payment date.<br/>**BEFORE** - If a scheduled payment date is a non-business day the payment will be made on the first business day before the scheduled payment date.<br/>**ON** - If a scheduled payment date is a non-business day the payment will be made on that day regardless.<br/>**ONLY** - Payments only occur on business days. If a scheduled payment date is a non-business day the payment will be ignored
   */
  nonBusinessDayTreatment?: ("AFTER" | "BEFORE" | "ON" | "ONLY") | null;
  /**
   * Indicates the number of payments remaining in the schedule. If both finalPaymentDate and paymentsRemaining are present then payments will stop according to the most constraining value. If neither field is present the payments will continue indefinitely
   */
  paymentsRemaining?: number | null;
  [k: string]: unknown;
}
/**
 * Indicates that the payment is a once off payment on a specific future date. Mandatory if recurrenceUType is set to onceOff
 */
export interface BankingScheduledPaymentRecurrenceOnceOff {
  /**
   * The scheduled date for the once off payment
   */
  paymentDate: string;
  [k: string]: unknown;
}
/**
 * A previously registered client aligned to the current version of the data standards
 */
export interface Client {
  [k: string]: unknown;
}
/**
 * A recipient record from the CDR Register aligned to the current version of the data standards
 */
export interface Recipient {
  [k: string]: unknown;
}
