/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A JSON schema for defining the changelog for test documentation
 */
export interface CDRTestDocumentationChangelogSchema {
  /**
   * The schema to which this file conforms.
   */
  schema: string;
  /**
   * The version of the file formatted using semver (without extensions)
   */
  fileVersion: string;
  /**
   * An optional url for the public GitHub repository
   */
  githubRepoUrl?: string;
  /**
   * A short title of the changelog file
   */
  title: string;
  /**
   * An optional description of the changelog file
   */
  description?: string;
  /**
   * A list of all the changes in the changelog
   */
  changes: {
    [k: string]: Change;
  };
}
/**
 * A single change in the changelog
 *
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^[a-zA-Z0-9_-]{21}$".
 */
export interface Change {
  /**
   * A unique identifier for the change
   */
  id: string;
  /**
   * A date when the change had occured
   */
  date: string;
  /**
   * An identifier for the Suite/Scenario/TestCase/Assertion where the change had occured
   */
  identifier: string;
  /**
   * The API version
   */
  version: string;
  /**
   * A semicolumn concatenated list of the identifier fields where the change had occured
   */
  field: string;
  /**
   * A description of the change
   */
  changeDescription: string;
  /**
   * The GitHub issue # which mandate this change
   */
  issueId: string;
}
